-- ShotMarket starter schema for Supabase.
-- Run this in Supabase Dashboard -> SQL Editor -> New query.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  balance numeric(12, 2) not null default 100 check (balance >= 0),
  is_admin boolean not null default false,
  admin_mode boolean not null default false,
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  total_bets integer generated always as (wins + losses) stored,
  win_rate integer generated always as (
    case
      when wins + losses = 0 then 0
      else round((wins::numeric / (wins + losses)::numeric) * 100)::integer
    end
  ) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.market_settings (
  id integer primary key default 1 check (id = 1),
  tracked_person_name text not null default 'Jia Xuan',
  grand_line numeric(10, 2) not null default 100 check (grand_line > 0),
  grand_start_date timestamptz not null default '2026-06-01 12:00:00+00',
  grand_end_date timestamptz not null default '2026-08-31 12:00:00+00',
  cumulative_shots numeric(10, 2) not null default 0 check (cumulative_shots >= 0),
  grand_status text not null default 'active' check (grand_status in ('active', 'resolved')),
  grand_winning_side text check (grand_winning_side in ('over', 'under', 'push')),
  updated_at timestamptz not null default now()
);

insert into public.market_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date timestamptz not null,
  line numeric(10, 2) not null check (line > 0),
  status text not null default 'active' check (status in ('active', 'pending', 'resolved')),
  actual_shots numeric(10, 2) check (actual_shots >= 0),
  winning_side text check (winning_side in ('over', 'under', 'push')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.bets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_id bigint references public.events(id) on delete cascade,
  market text not null check (market in ('event', 'grand')),
  side text not null check (side in ('over', 'under')),
  stake numeric(12, 2) not null check (stake > 0),
  status text not null default 'open' check (status in ('open', 'won', 'lost', 'push')),
  payout numeric(12, 2) not null default 0 check (payout >= 0),
  created_at timestamptz not null default now(),
  constraint event_market_requires_event check (
    (market = 'event' and event_id is not null)
    or
    (market = 'grand' and event_id is null)
  )
);

create table if not exists public.shot_history (
  id bigint generated by default as identity primary key,
  shot_date timestamptz not null,
  cumulative_total numeric(10, 2) not null check (cumulative_total >= 0),
  created_at timestamptz not null default now()
);

insert into public.shot_history (shot_date, cumulative_total)
values ('2026-06-01 12:00:00+00', 0)
on conflict do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base_username text;
  candidate_username text;
begin
  base_username := coalesce(
    nullif(new.raw_user_meta_data ->> 'username', ''),
    nullif(split_part(new.email, '@', 1), ''),
    'player'
  );
  base_username := lower(regexp_replace(base_username, '[^a-zA-Z0-9_]+', '-', 'g'));
  base_username := trim(both '-' from base_username);

  if base_username = '' then
    base_username := 'player';
  end if;

  candidate_username := left(base_username, 32);

  if exists (select 1 from public.profiles where username = candidate_username) then
    candidate_username := left(base_username, 23) || '-' || substring(new.id::text from 1 for 8);
  end if;

  insert into public.profiles (id, username)
  values (new.id, candidate_username)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (select is_admin from public.profiles where id = auth.uid()),
    false
  );
$$;

create or replace function public.place_bet(
  p_market text,
  p_side text,
  p_stake numeric,
  p_event_id bigint default null
)
returns public.bets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_balance numeric;
  v_bet public.bets;
begin
  if v_user_id is null then
    raise exception 'Please log in first.';
  end if;

  if p_side not in ('over', 'under') then
    raise exception 'Invalid market side.';
  end if;

  if p_stake is null or p_stake <= 0 then
    raise exception 'Stake must be greater than zero.';
  end if;

  select balance
  into v_balance
  from public.profiles
  where id = v_user_id
  for update;

  if not found then
    raise exception 'Profile not found.';
  end if;

  if v_balance < p_stake then
    raise exception 'Insufficient balance.';
  end if;

  if p_market = 'event' then
    if p_event_id is null then
      raise exception 'Event is required.';
    end if;

    perform 1
    from public.events
    where id = p_event_id and status = 'active';

    if not found then
      raise exception 'This market is closed.';
    end if;
  elsif p_market = 'grand' then
    if p_event_id is not null then
      raise exception 'Grand market bets cannot include an event.';
    end if;

    perform 1
    from public.market_settings
    where id = 1 and grand_status = 'active';

    if not found then
      raise exception 'The grand market is already resolved.';
    end if;
  else
    raise exception 'Invalid market.';
  end if;

  update public.profiles
  set balance = balance - p_stake
  where id = v_user_id;

  insert into public.bets (user_id, event_id, market, side, stake)
  values (v_user_id, p_event_id, p_market, p_side, p_stake)
  returning * into v_bet;

  return v_bet;
end;
$$;

revoke all on function public.place_bet(text, text, numeric, bigint) from public;
grant execute on function public.place_bet(text, text, numeric, bigint) to authenticated;

alter table public.profiles enable row level security;
alter table public.market_settings enable row level security;
alter table public.events enable row level security;
alter table public.bets enable row level security;
alter table public.shot_history enable row level security;

drop policy if exists "signed in users can read profiles" on public.profiles;
create policy "signed in users can read profiles"
on public.profiles for select to authenticated
using (true);

drop policy if exists "admins can manage profiles" on public.profiles;
create policy "admins can manage profiles"
on public.profiles for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "signed in users can read settings" on public.market_settings;
create policy "signed in users can read settings"
on public.market_settings for select to authenticated
using (true);

drop policy if exists "admins can manage settings" on public.market_settings;
create policy "admins can manage settings"
on public.market_settings for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "signed in users can read events" on public.events;
create policy "signed in users can read events"
on public.events for select to authenticated
using (true);

drop policy if exists "admins can manage events" on public.events;
create policy "admins can manage events"
on public.events for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "signed in users can read bets" on public.bets;
create policy "signed in users can read bets"
on public.bets for select to authenticated
using (true);

drop policy if exists "admins can manage bets" on public.bets;
create policy "admins can manage bets"
on public.bets for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "signed in users can read shot history" on public.shot_history;
create policy "signed in users can read shot history"
on public.shot_history for select to authenticated
using (true);

drop policy if exists "admins can manage shot history" on public.shot_history;
create policy "admins can manage shot history"
on public.shot_history for all to authenticated
using (public.is_admin())
with check (public.is_admin());
